import Layout from "./layout"
import Hero from "./hero/Hero"
import About from "./About"
import Services from "./Services"
import Projects from "./Projects"
import Survey from "./Survey"
import Slider from "./reviewSlider/Slider"
import Algolia from "./Algolia"
import GridProjects from "./GridProjects"
export { Layout, Hero, About, Projects, Survey, Slider, Algolia, GridProjects, Services }
